export const TOKENS = {
    colors: {
        light: {
            bgPrimary: '#FFFFFF',
            bgSecondary: '#F3F3F3',
            bgElevated: '#FFFFFF',
            border: '#DDDBDA',
            borderStrong: '#C9C7C5',
            textPrimary: '#181818',
            textSecondary: '#514F4D',
            textMuted: '#706E6B',
            accent: '#0176D3',
            accentHover: '#014486',
            accentText: '#FFFFFF',
            success: '#2E844A',
            successBg: '#EEF4EE',
            warning: '#C57A00',
            warningBg: '#FEF4E3',
            error: '#C23934',
            errorBg: '#FAEEED',
            badgeOpenBg: '#EEF4EE',
            badgeOpenText: '#2E844A',
            badgeExclusiveBg: '#FEF4E3',
            badgeExclusiveText: '#C57A00',
        },
        dark: {
            bgPrimary: '#0A0A0A',
            bgSecondary: '#1A1A1A',
            bgElevated: '#222222',
            border: '#3E3E3C',
            borderStrong: '#514F4D',
            textPrimary: '#F3F3F3',
            textSecondary: '#C9C7C5',
            textMuted: '#8E8884',
            accent: '#1B96FF',
            accentHover: '#57B3FF',
            accentText: '#032D60',
            success: '#41B658',
            successBg: '#1B3A22',
            warning: '#FFB75D',
            warningBg: '#3A2800',
            error: '#FE5B4C',
            errorBg: '#3A0F0F',
            badgeOpenBg: '#1B3A22',
            badgeOpenText: '#41B658',
            badgeExclusiveBg: '#3A2800',
            badgeExclusiveText: '#FFB75D',
        },
    },
    typography: {
        fonts: {
            body: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
            mono: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
        },
        sizes: {
            xs: '11px',
            sm: '13px',
            base: '14px',
            md: '16px',
            lg: '20px',
            xl: '24px',
            '2xl': '32px',
        },
        weights: {
            regular: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
        },
    },
    spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
    },
    borders: {
        radius: {
            sm: '4px',
            md: '6px',
            lg: '8px',
            pill: '100px',
        },
        shadows: {
            sm: '0 1px 2px rgba(0,0,0,0.10)',
            md: '0 2px 6px rgba(0,0,0,0.12)',
            lg: '0 4px 16px rgba(0,0,0,0.14)',
        },
    },
} as const
